package com.example.instamate.Models

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.ArrayList

data class Posts (var username: String? = "", //name of poster
                  var image:String?="", //image url
                  var caption: String?="", //post caption
                  var likes: Int?= 0, //number of likes
                  var userid: String?="", //userid
                  var profileImage: String?= "", //profile image of user
                  val likers: ArrayList<String> = ArrayList(),//mutable list for post likers,
                 // Written on the server
                  @ServerTimestamp val timeStamp: Timestamp? = null, //time of post
    //    // FirestoreID is generated by firestore, used as primary key
                @DocumentId var firestoreID: String = "", //postid
    )